Import('env')

env.Append(CPPPATH = ['utilities'])
env.Prepend(LIBS = 'gutilities')

sources = Split("""
	utilities.cc
	defineOptions.cc
	""")

env.Library(source = sources, target = "#lib/gutilities")


