/* XPM */
static const char * infos_xpm[] = {
"96 84 257 2",
"  	c None",
". 	c #0C0E0A",
"+ 	c #130D0C",
"@ 	c #100F04",
"# 	c #110E12",
"$ 	c #0F0F18",
"% 	c #170E14",
"& 	c #130F1C",
"* 	c #150F18",
"= 	c #131023",
"- 	c #1B0F18",
"; 	c #181312",
"> 	c #1C1313",
", 	c #151614",
"' 	c #17160F",
") 	c #19141D",
"! 	c #1B150F",
"~ 	c #15161D",
"{ 	c #1C1423",
"] 	c #1E141E",
"^ 	c #171622",
"/ 	c #1A1716",
"( 	c #19171A",
"_ 	c #1D161B",
": 	c #18181F",
"< 	c #1C1820",
"[ 	c #211819",
"} 	c #1B1B14",
"| 	c #1E1921",
"1 	c #1F1A15",
"2 	c #1E1A19",
"3 	c #1B1C1A",
"4 	c #1D1C1F",
"5 	c #211A2A",
"6 	c #211C17",
"7 	c #201C1B",
"8 	c #221B20",
"9 	c #1B1D24",
"0 	c #1D1C29",
"a 	c #1F1E18",
"b 	c #231D18",
"c 	c #221E1D",
"d 	c #241E19",
"e 	c #231F1E",
"f 	c #291E1A",
"g 	c #232116",
"h 	c #22211A",
"i 	c #24201F",
"j 	c #26201B",
"k 	c #281F20",
"l 	c #202220",
"m 	c #272024",
"n 	c #252120",
"o 	c #252120",
"p 	c #27211C",
"q 	c #23212F",
"r 	c #23231C",
"s 	c #242225",
"t 	c #28221D",
"u 	c #2D1F30",
"v 	c #25222A",
"w 	c #24241D",
"x 	c #272322",
"y 	c #2B2332",
"z 	c #2C2621",
"A 	c #2B2625",
"B 	c #292921",
"C 	c #2B2732",
"D 	c #282931",
"E 	c #282A28",
"F 	c #2B292D",
"G 	c #2E2A29",
"H 	c #2E2C1C",
"I 	c #322A2F",
"J 	c #302D22",
"K 	c #342B2B",
"L 	c #303029",
"M 	c #2F302E",
"N 	c #332F2E",
"O 	c #36302A",
"P 	c #3E3037",
"Q 	c #3B3235",
"R 	c #3B342F",
"S 	c #37362A",
"T 	c #363539",
"U 	c #393534",
"V 	c #353734",
"W 	c #37372F",
"X 	c #3D3B28",
"Y 	c #3F3C19",
"Z 	c #3F3A3A",
"` 	c #403D21",
" .	c #3E3C34",
"..	c #3B3D3B",
"+.	c #473F34",
"@.	c #454140",
"#.	c #444336",
"$.	c #44443C",
"%.	c #47452C",
"&.	c #4B4244",
"*.	c #474533",
"=.	c #434542",
"-.	c #4A4625",
";.	c #4A4544",
">.	c #4A491F",
",.	c #474946",
"'.	c #524B18",
").	c #51493E",
"!.	c #504E13",
"~.	c #4D4C32",
"{.	c #4E4A49",
"].	c #4E4C3B",
"^.	c #4C4C44",
"/.	c #53513F",
"(.	c #5B512B",
"_.	c #545339",
":.	c #515350",
"<.	c #54534B",
"[.	c #575250",
"}.	c #5B5151",
"|.	c #5B5622",
"1.	c #595835",
"2.	c #5D5B1E",
"3.	c #5C5A3D",
"4.	c #605A32",
"5.	c #5B5C2E",
"6.	c #595A52",
"7.	c #585A57",
"8.	c #5D5959",
"9.	c #656037",
"0.	c #656141",
"a.	c #5F605D",
"b.	c #666161",
"c.	c #656638",
"d.	c #636462",
"e.	c #6C6833",
"f.	c #6F6B2F",
"g.	c #676966",
"h.	c #6A6961",
"i.	c #6D6867",
"j.	c #71701D",
"k.	c #716F29",
"l.	c #75703A",
"m.	c #736E6E",
"n.	c #747344",
"o.	c #6F716D",
"p.	c #787438",
"q.	c #7B7A24",
"r.	c #7C7933",
"s.	c #777875",
"t.	c #84810E",
"u.	c #83802F",
"v.	c #888037",
"w.	c #858142",
"x.	c #87832B",
"y.	c #858523",
"z.	c #827D7D",
"A.	c #7D7F7C",
"B.	c #848439",
"C.	c #83862C",
"D.	c #8B8836",
"E.	c #898584",
"F.	c #868885",
"G.	c #928F22",
"H.	c #91902F",
"I.	c #919038",
"J.	c #978E3E",
"K.	c #918D8D",
"L.	c #99972A",
"M.	c #9C9918",
"N.	c #8F918E",
"O.	c #999640",
"P.	c #999493",
"Q.	c #959794",
"R.	c #A09D3C",
"S.	c #98969A",
"T.	c #A69F35",
"U.	c #9FA137",
"V.	c #A2A130",
"W.	c #A8A515",
"X.	c #A8A904",
"Y.	c #A29D9D",
"Z.	c #A8A72A",
"`.	c #9EA09D",
" +	c #AAA4A3",
".+	c #A5A7A4",
"++	c #B0B12F",
"@+	c #B4B125",
"#+	c #B6B51C",
"$+	c #ADAFAC",
"%+	c #B4AFB0",
"&+	c #C0BE16",
"*+	c #BFBD28",
"=+	c #BFBC34",
"-+	c #BAB6B8",
";+	c #B6B8B4",
">+	c #CBC21E",
",+	c #C8C802",
"'+	c #C8C61A",
")+	c #C7C627",
"!+	c #BDBFBB",
"~+	c #CECD26",
"{+	c #D3CE16",
"]+	c #C7C1C0",
"^+	c #C2C4C1",
"/+	c #D0D119",
"(+	c #C5C3C7",
"_+	c #D5D509",
":+	c #DDD60F",
"<+	c #C9CBC7",
"[+	c #D9D724",
"}+	c #DADA12",
"|+	c #CDCBCF",
"1+	c #D0CBC9",
"2+	c #CED0CD",
"3+	c #E6DE11",
"4+	c #E0DF20",
"5+	c #E5E415",
"6+	c #D4D6D3",
"7+	c #EAE700",
"8+	c #D9D7DB",
"9+	c #DCD7D5",
"0+	c #E7EA03",
"a+	c #D9DBD8",
"b+	c #EFEB00",
"c+	c #F0ED12",
"d+	c #EEF100",
"e+	c #FAEE00",
"f+	c #E0E2DF",
"g+	c #F7F300",
"h+	c #E8E3E2",
"i+	c #E6E3E8",
"j+	c #F4F608",
"k+	c #E6E8E4",
"l+	c #FEF800",
"m+	c #F9FA00",
"n+	c #FFF900",
"o+	c #FAFB00",
"p+	c #FFFA00",
"q+	c #FBFC00",
"r+	c #FCFD00",
"s+	c #FEFE00",
"t+	c #EAEDE9",
"u+	c #F1EBEA",
"v+	c #FFFF01",
"w+	c #F1EEF3",
"x+	c #F7F1F0",
"y+	c #F1F3F0",
"z+	c #F9F6FB",
"A+	c #F7F9F6",
"B+	c #FDF8F6",
"C+	c #FFFCFB",
"D+	c #FCFEFB",
"E+	c #FFFEF5",
"F+	c #FFFDFF",
"G+	c #F9FFFF",
"H+	c #FEFFFC",
"                    1+^+^+]+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+^+]+^+<+a+                    ",
"            1+S / > 7 b d h b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b c c a ( ! h E.              ",
"        -+> a h : D !.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.2.%.^ [ j , <.          ",
"      Q.7 b 8 &+r+r+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+r+r+c+*.7 r E         ",
"    E 7 1 ++r+n+q+n+n+q+q+n+n+n+n+n+n+n+n+n+n+n+n+m+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+q+q+q+n+r+V.E f ..f+    ",
"  S.j 7 ++n+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+q+q+n+q+q+r+n+n+n+n+n+n+q+n+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+q+r+r+| d b     ",
"  1 b  .r+n+n+q+m+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+q+q+{+7 e !+  ",
"1+} W [+n+q+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+n+q+n+q+m+n+q+n+n+n+r+q+n+n+n+n+n+n+m+m+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+r+I h  .  ",
"z.i U.r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+0.@+j+r+n+q+w.r+r+r+@+F r+n+q+n+r+r+n+q+q+/+#+r+n+n+q+n+n+n+n+n+q+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r.4 ;   ",
"[.i _+r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+c+/ < _.m+7+3 k.m+_+} j < *+r+r+W H.r+r+:+_ 2 ( #+r+q+q+n+n+r+n+q+q+q+n+n+n+q+q+n+n+n+n+n+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+@+< }   ",
"{.e d+r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+= h 3 c.0.h ^ j.].l h r F M.,+_ y r+:+/.h i r l 7+r+n+r+r+)+q+q+r+X.r+q+q+n+m+n+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+/+: 1   ",
",.d e+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+(._ g i j i l d h j p f i f c r i N k l j l p h 3 F 5+#.| a W.r+y < 3.r+n+q+r+~+r+q+q+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+:+_ 1   ",
";.h b+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+7+F i r n p h h i i r r j r i r j i h j i j r n r j 4 j r h m 4 r h 8 =+r+[+q >.q+n+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+( 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+W.r j r p i i i i j i i i i r i i p i p i i i i i i i i i i i r l i i 8 7 i { L.r+)+W.Z.q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+^ i i i j i i i n e i i i i i i n i n i i i i i i i i i i i j h d h p h i h 4 ^ } C r+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+r+L l j p p j i i i i i i i i i i i i i i i i i i i i i i i i i i i p p w h i r h ].5+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+q+L.j i g...A / i i i i i i i i i i i i i i i n i i i i i i i j h p j j i p i i { r+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+5+< j  +H+H+A+]+E.N , } p j i i c i e j j p e i i n i i i i j i i i j h j j 7 Z.n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+r+n+q+r+: e  +H+H+Y.E j ;.9+u+P.V x ; e i n p i x i i t p t b 1 ! ! 2 i E E e l c q r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+X 2 .+;+L 8.t+D+6+V . H+H+H+A+$+s.l } a w V ,.o.Q.;+9+k+y+H+H+H+F+{.} n T ~+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+r+O.9 %+b Y.H+H+H+H+H+H+H+H+H+H+F+H+H+H+H+H+H+H+H+2+Q.d.A.Q.H+H+H+F+V 1 } :+r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+q+r+}+{+0  +i+H+A+6+2+9+y+H+H+H+H+H+H+H+H+H+H+H+H+H+a+r + 1 ; + ,.w+H+H+E 7 0 r+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+:+W R < A F.8.h r 7.g.a.A + ,.y+H+H+H+H+H+H+H+H+H+H+f+t+H+H+H+H+<+; p H+! d v.n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+l &.H+|+U ! .+u+H+H+H+H+H+H+^+; N H+H+H+H+H+H+H+Y.:.+ ! 1 ; } ..a+H+.+P., ^ r+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+g+4 ^+F+@.+ A+H+F+H+H+H+H+G+H+H+H+.+n H+H+H+H+u++ g.<+H+H+H+H+B+6+L $.!+G+; $.R.r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+_+[.H+.+,.y+H+H+H+H+H+H+H+H+H+H+H+H+o.A.H+H+;.. k+H+H+H+H+H+H+H+H+H+Q.} @.} [.h.c.r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+@+z.H+. F+H+H+H+H+H+H+H+H+H+H+H+H+H+H++ z.N.:.y+H+H+H+H+H+H+H+H+H+H+H+C+! y+H+H+& Z.n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+U.P.i+Z H+H+H+H+H+H+H+H+<+H+H+H+H+H+H+d.j . F+H+H+H+H+H+H+H+H+H+H+H+H+H+<+@.A+H+& t.n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+U.Q.$+F.H+H+H+H+H+H+A.; b ' F.H+H+H+H+!+j g.H+H+H+H+H+H+H+H+H+H+H+H+H+H+H++ m.H+& t.n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+,+A.Q.Y.H+H+H+H+H+H+a j p b x H+H+H+H+1+A 2+H+H+H+H+H+H+y+2+f+H+H+H+H+H+H+,.A H+$ Z.n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+}+7.-+z.H+H+H+H+H+H+o.; j . s.H+H+H+H+;+! f+H+H+H+H+H+t+; b 1 .+D+H+H+H+H+s.! D+H :+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+5+Z ;+8.H+H+H+H+H+H+k+o.} o.t+H+H+H+H+N.. k+H+H+H+H+H+;+c j j :.y+H+H+H+H+m.! t+>.q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+) !+. H+H+H+H+H+H+H+H+H+H+H+H+H+H+H+E } 1+H+H+H+H+H+!+j p j :.B+H+H+H+H+;.E F.Z.r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+< g.7..+H+H+H+H+H+H+H+H+H+H+H+H+H+1+V S.d.F+H+H+H+H+H+d.M ..H+H+H+H+H+H+. A.3 e+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+5.( H+. :.H+H+F+H+H+H+H+H+H+H+H+A++ y+H++ H+H+H+H+H+H+H+H+H+H+H+H+H+H+!+[.w+l r+q+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+2 H+i+6.;.H+H+H+H+H+H+H+H+C+b.+ <+H+H+.+@.k+H+H+H+H+H+H+H+H+H+H+H+D++ H+m.V.n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+M.A.H+H+`.@ K .+k+u+k+;+m.+ F.D+H+G+G+H+:.. a+H+H+H+H+H+H+H+H+H+z.! 1+E.# r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+r+r+# B+H+H+z.( ` W L W o. +H+6+, H+G+H+t+H+y+2 [.$+H+H+H+H+t+<+w :.9+H+# r.q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+H.:.t+H+; 0.R.F.H+H+H+H+H+A+7.]+H+y+3 H+H+H+;+h.2 , a % n }.f+H+H+b.I.r+q+n+q+n+n+n+n+n+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+n+r+].& v u.q+j+N y+H+D+H+H+H+$+s.k+Z <+H+H+H+H+H+H+<.{ &+z.G+H+H+9+9 r+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+n+q+n+r+r+d+n+n+r+# S.F+H+H+H+H+D+G ..i H+H+H+H+H+H+y+{ #+:+P i+H+[.& m+n+q+q+n+n+n+n+n+n+n+n+n+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+q+q+n+n+n+r+G $.H+H+H+H+H+H+1 E 9+H+H+H+H+H+H+<.#+r+r+I ( ) k.g+q+n+q+q+n+n+n+n+n+n+n+n+r+r+r+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+n+q+n+n+q+q+r+(.v H+H+H+H+H+F+2 s.B+H+H+H+H+H+H+/ j+r+q+~+9.4.r+r+r+q+n+n+n+n+n+n+n+q+n+n+m+c.4.5+q+n+n+q+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+V.& H+H+H+H+H+H+;+H+H+H+H+G+G+H+!+(.r+n+m+n+q+n+n+n+n+n+n+n+n+n+n+q+n+n+r+q+# !+2+{ g+r+n+n+r+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+j+` k+H+H+H+H+H+H+H+H+H+H+H+H+]+2 g+q+q+n+n+n+n+q+n+n+n+n+n+n+n+n+q+n+r+D.$ <+C+H+,.:+r+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+J.N.H+H+H+H+H+H+H+H+H+H+H+G+_ ~.r+q+n+n+q+n+n+q+n+n+n+n+n+n+n+n+n+q+V.A (+F+H+]+) r+r+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+3+Z H+H+6+=.f+H+H+H+H+H+H+(+#.d+n+q+n+n+n+n+n+n+n+n+q+q+n+n+n+n+r+#+8 H+H+H+Z & r+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+r+= H+t+; a+H+H+H+H+H+H+H+a 7+r+n+n+n+n+n+n+n+n+n+n+n+m+n+r+n+r+N / H+G+H+{.$.5+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+r+x z+!+;+. V <+1+`.. H+|+X q+n+q+n+n+n+n+n+n+n+n+n+n+n+q+r+[+W G {.E.f+b.g d.# 5+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+e.!+H+H+H+2+[.<.A.F+2+l 7+q+m+n+n+n+n+n+n+n+n+n+n+n+n+~+& W %+A+w+Q.> h G+H+h+Y n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+,+b.H+F+H+H+C+H+H+F+k S r+n+q+q+n+n+n+n+n+n+q+n+n+r+7+# F+H+H+H+C+k+W b H+A.! G n+n+m+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+g+3 ^+H+H+H+H+H+G+9+M 5+q+n+n+n+n+n+n+n+n+n+n+n+q+*+8 f+H+H+H+A + G N.A+^.W !+o.D.r+n+q+q+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+& `.H+H+H+H+H+H+z.x.r+n+q+n+q+n+n+n+n+n+q+n+n+q+e.% H+H+H+^+! z.f+H+<++ 6+H+6+%.m+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+q+E {.H+H+H+F+G+H+$ r+q+n+n+n+n+n+n+n+n+n+n+n+q+n+. S.H+H+H+t H+H+H+1 ! x+H+H+w+4 =+m+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+k.* H+H+C+H+H+E.u.n+n+n+n+n+n+n+n+n+n+n+n+n+n+V.m.H+H+a+H+P.W A., $+H+C+6+8.@ 0.j+n+q+r+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+n+~+[ H+G+H+H+K.$ r+q+n+n+n+n+n+n+n+n+n+n+n+q+r+` a+H+y+a 2+H+9+z.m.H+H+;.a z.G+^ j.n+n+q+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+q+q+m+3.(+H+H+G+# p.q+q+q+n+n+n+n+n+n+n+n+n+n+m+r+^ H+H+H+h M H+H+H+; x + N.B+H+w+= j.q+n+q+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+q+n+q+r+r+>+o.H+H+P.k.q+n+n+q+n+n+n+n+n+n+n+n+n+n+n+r+* H+H+H+B+.+, H+H+F+h a+H+!+[._ ,+n+q+q+r+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+r+r+7+I.k.*. .R N H+H+; r+r+q+q+q+n+n+n+n+n+n+n+n+n+q+n+r+: H+H+H+H+H+H+H+H+G+M a w ) S r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+m+n+q+r+r+>+T : c e i r l i , H+`.j 0 #.5+r+q+q+n+n+q+n+n+n+n+n+n+r+j+3 H+H+H+H+H+F+H+H+w+:.m 1.r+r+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+r.u a e p r i p j p i c P.2 p p j 2 W Z.r+q+r+n+n+n+n+n+n+q+r+~+;.H+H+H+H+H+H+m.F s &+r+r+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+q+r+c+0 h r h j l p i i i i p j b j h h r d l d  .r+r+m+n+n+n+n+n+q+~+i i+H+H+E+x+F.# M.7+r+n+q+n+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+r+%.: h i r k p h h j i i x i p j j p i h r r l e 0 H.r+n+n+n+n+n+r+0  .F+H+H+H+' X r+n+n+q+n+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+n+)+: h i h r h h l i i i i p p p p p i h p p j h i a 4 r+n+n+n+n+n+r+# `.H+H+H+t+) ++n+n+q+n+r+q+n+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+q+n+r+_+( k p m i i i i i i i i i i i i i i n i i n i p j i d m r+n+q+n+r+` ;+H+H+H+H+A _+r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+r+0.] k r i i i i i i n i i i i i i i i i i i i i i h g r j l *.5+n+r+}+w H+H+H+H+%+%.r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+q+&+h g p h j h i i i i i i i i i i i i i i i i i i i r r i j i i 0 r+@+< k+H+H+H+S.# m+n+m+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+q+n+n+n+n+q+r+^ j i h j j j i i i i i i i i i i i i i i i i i i i i i i i i f h H.$ h.F+H+H+H+# r.q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+q+n+q+m+q+c.i h i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i j h F.H+H+H+H+d.L.r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+q+n+n+r+3.( i g p i i i i i i i i i i i i i i i i i i i i i i i i i i i i i h 7 H+H+H+F+y+^ r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+q+n+q+n+r+< r j r r i i i p i i i i i i i i i i i i i i i i i i i i i i i i i a 9+H+H+H+i+S '+q+n+q+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< 1   ",
",.e b+r+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+y.e h p p i i i i i i i i i i i i i i i i i i i i i i i i n i i i i ; 7.H+H+H+H+F E r+n+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+_+< }   ",
",.g b+r+q+n+n+n+n+n+n+n+n+n+n+q+m+m+r+q p i j j j i i i i i i i i i i i i i i i i i i i i i i i i j i j j E.H+H+H+H+(+R 5+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+:+< /   ",
",.j c+r+q+n+n+n+n+n+n+n+n+n+n+n+q+r+r+_ i h i p j i i i i i i i i i i i i i i i i i i i i i i i i j d p / x+H+H+H+H+8.Z.r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+}+( 7   ",
":.d }+r+q+n+n+n+n+n+n+n+n+n+n+n+m+r+~+l j j p i i i i i i i i i i i i i i i i i i i i i i i i i i e i i A.H+H+G+H+y+( r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+@+( !   ",
"s.h R.r+n+n+n+n+n+n+n+n+n+n+n+n+n+r+j.r e j n r p i i i i i i i i i i i i i i i i i i i i i i i n c i 1 y+H+H+H+a+V U r+n+m+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+w.3 !   ",
"1+g X 5+n+n+n+n+n+n+n+n+n+n+n+n+n+{+T p i i i n i i i i i i i i i i i i i i i i i i i i i i i i i i i i 2 s.f+H+A e ] r+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+m+q+n+r+F a ..  ",
"  _ 4 %.r+q+n+n+q+q+n+n+n+n+n+n+n+X.{ r i i i i i i i i i i i i i i i i i i i i i i i i i i i i n i n i i j 2 :.h j 4 r+n+m+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+n+4+} h ;+  ",
"  F.h e '+q+n+r+n+q+n+n+n+n+n+q+q+c.( r i i i i i i i i i i i i i i i i i i i i i i i i i i i i i e i i i j p p p i ( r+n+q+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+n+n+q+r+s g 3     ",
"    p b / {+r+n+n+n+n+n+n+n+n+n+r+).2 i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i n i i j p e i ( r+n+q+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+n+q+r+*+U r U a+    ",
"      F.b a q '+r+r+r+q+q+q+n+q+r+W 7 e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e ( g+r+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+n+r+r+r+r+1.3 p l         ",
"         +' h a < N 0.C.y.y.x.y.C.W L O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O N x.y.C.y.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.y.x.p.].( ( h ! $.          ",
"            -+z 1 b h l i h j h d c i e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e i h j i h h j j j j j j j j j j j j j j j j j j d i i j } ' m.              ",
"                    %+.+ +.+ +.+.+.+ + +.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+.+ + + + +.+.+ + + + + + + + + + + + + + + + + + +.+ +$+a+                    "};
