#!/bin/csh -f

if($1 == "-h" || $1 == ""  || $2 == ""  || $#argv != 2) then
 echo " "
 echo "Usage:   "
 echo  "  >> drop_from_table_volume tablename volumename"
 echo  "     drops <volumename> from table <tablename>"
 echo " "
 exit 0
endif

set table = $1
set vname = $2

rm -f tmp.txt
echo  "use clas12_geometry;"                             > tmp.txt
echo  "delete from $table where name ="'"'$vname'"'  >> tmp.txt 

echo Deleting $vname from $table".  Are you sure? y/n"
set confirm = $<
if($confirm == "y") then
  mysql -h clasdb.jlab.org -u clasuser                < tmp.txt 
  echo $vname deleted from $table
endif

rm -f tmp.txt


