#!/bin/csh -f

if($1 == "-h") then
 echo " "
 echo "Usage:   "
 echo  "  >> show_banks"
 echo  "     lists current banks"
 echo " "
 exit 0
endif

set table = $1
rm -f tmp.txt
echo  "use clas12_banks;" > tmp.txt
echo  "select id, identifiers, minEnergy, TimeWindow, ProdThreshold, MaxStep from SDId;" >> tmp.txt 
mysql -h clasdb.jlab.org -u clasuser < tmp.txt 
rm -f tmp.txt




