#!/bin/csh -f

set tables = (HTCC)

if($1 == "clean") then
  foreach t ($tables)
    rm -rf $t*.txt
  end
  rm -rf tmp.txt
else
  foreach t ($tables)
		rm -rf $t*.txt
  end
  rm -rf tmp.txt

  rm HTCC*.txt 
  rm PMTajrp.txt
  rm AllMirrors.txt

  # Default database - first argument defines new one
  set database = $1
  if($database =="") then
    set database = "clas12_geometry"
  endif

  # creates files. Should match the tables name above
	
  #./Mirror1.pl
  #./Mirror2.pl
  #./Mirror3.pl
  #./Mirror4.pl
  ./PMTs_ajrp.pl
  ./MotherVolume.pl
  ./MirrorsAll_ajrp.pl

  

  # Remaking the tables
  foreach t ($tables)
    echo "y" | $GEMC/database_io/drop_geo_table  $t   $database
    $GEMC/database_io/create_new_geo_table  $t  $database
  end

  rm -rf tmp.txt
  echo use $database";" > tmp.txt;
  foreach t ($tables)
    #echo  LOAD DATA LOCAL INFILE \'HTCCnateM1.txt\'   into TABLE $t";" >> tmp.txt
    #echo  LOAD DATA LOCAL INFILE \'HTCCnateM2.txt\'   into TABLE $t";" >> tmp.txt
    #echo  LOAD DATA LOCAL INFILE \'HTCCnateM3.txt\'   into TABLE $t";" >> tmp.txt
    #echo  LOAD DATA LOCAL INFILE \'HTCCnateM4.txt\'   into TABLE $t";" >> tmp.txt
    echo  LOAD DATA LOCAL INFILE \'PMTajrp.txt\'      into TABLE $t";" >> tmp.txt
    echo  LOAD DATA LOCAL INFILE \'HTCC.txt\'         into TABLE $t";" >> tmp.txt
    echo  LOAD DATA LOCAL INFILE \'AllMirrors.txt\'    into TABLE $t";" >> tmp.txt
    echo update $t" set time=NOW() where time=0;" >> tmp.txt;
  end

  mysql -h clasdb.jlab.org -u $GEMC_USER < tmp.txt


endif

