import os
from util import scanFiles
env = Environment(ENV=os.environ)

pdf = env.PDF(target  = 'gemc_book.pdf',  source = 'gemc_book.tex')
#html = env.Command('gemc_book.html', 'gemc_book.tex', "go_htlatex $SOURCE");

#Depends(html, pdf)

cleans = scanFiles('.', accept=["gemc_book*", "*.aux"], reject=[".tex"])
#rint "to remove: ", cleans;

Clean('gemc_book.html', cleans)
