Import('env')

env.Prepend(LIBS = 'gsensitivity')

sources = Split("""
	gHit.cc
    gTouchable.cc
    gSensitiveDetector.cc
	utilities.cc
	""")

env.Library(source = sources, target = "#lib/gsensitivity")


