from init_env import init_environment

env = init_environment("qt5 mlibrary")
env.Append(LIBPATH = ['lib'])



# utilities
env.Append(CPPPATH = 'utilities')
env.Prepend(LIBS = 'utilities')
utilsSrc = Split("""
	utilities/utilities.cc
	""")
utils = env.Library(source =utilsSrc, target = "lib/utilities")



gsources = Split("""
	gemc.cc
	""")

gemc = env.Program(source = gsources, target = "gemc")

