from init_env import init_environment

env = init_environment("qt5 mlibrary")
env.Append(LIBPATH = ['lib'])
Export('env')



# utilities
SConscript('utilities/SConscript', 'env')

# gui
SConscript('gui/SConscript', 'env')


gsources = Split("""
	gemc.cc
	""")

gemc = env.Program(source = gsources, target = "gemc")

