Import('env')

env.Append(CPPPATH = ['run'])
env.Prepend(LIBS = 'grun')

sources = Split("""
	GRun.cc
    GRunAction.cc
    GActionInitialization.cc
	""")

env.Library(source = sources, target = "#lib/grun")


